name: Testing

on:
  pull_request:
    branches: [main]

jobs:
  Install-Dependencies:
    name: Install and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: bahmutov/npm-install@v1
      - name: Run Monkey Tests
        run: npx playwright test

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2