name: Meterian

on:
  pull_request:
    paths:
      - '**/*.json'

jobs:
  scan:
    name: Vulnerability scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run scan
        uses: MeterianHQ/meterian-github-action@v1.0.10
        env:
          METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
        with:
          cli_args: --project-tags=monkeytesting --min-security=100 --min-stability=100 --min-licensing=100